import type { Metadata } from "next";
import { Geist, Geist_Mono ,Instrument_Sans} from "next/font/google";
import "./globals.css";
import { Providers } from "../providers/wagmi-provider";
import '@rainbow-me/rainbowkit/styles.css';
import React from "react";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const instrumentsSans = Instrument_Sans({
  variable: "--font-instrument-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Kyrex",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${instrumentsSans.variable} antialiased`}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
