[package]
version = "0.1.0"
name = "aadhaar-program"

edition = "2021"

[dependencies]
alloy-sol-types = { workspace = true }
sp1-zkvm = "4.0.0"
aadhar-lib = { path = "../lib" }
sha2 = "0.10.8"
pem = "1.0"
signature = "2.2.0"
rsa = "0.9.7"
